### ISSUE TITLE
[BUG]: Clashes with ScarfaceHook, mouse cursor stuck on screen, rebindable walk key?

### ISSUE THREAD

**Issue by ca5dx** [GangstaTeam/GangstaPatch#1]
### Description:

Just as the title says. Using ScarfaceHook alongside this makes the cursor stay on the screen, and if you alt tab out and go back in, you end up walking because the walk key is binded to Alt. Can it be rebinded?

**Comment by sneakyevil** [comment]
Whatever is ScarfaceHook doing with the game is not my considering of fixing for the patch. I removed part of code in game that is handling the cursor since DirectInput is already doing it and alt-tabbing with that code still been used would cause cursor been invisible while alt-tabbing from the game.

The walk key can be easily "unstuck" by just pressing it once. Rebinding mid game is kind of out of the scope based on how the game handles the binding of keys, but will probably add it as INI option to change name of the key otherwise needing to restart whole game when changing the key in settings.

**Comment by sneakyevil** [comment]
Just pushed commit with option to change the walk binding to different key via INI file. 
Example is in `README.md` it takes generic english key names.

**Comment by ca5dx** [comment]
silentpatch does the same things your patch does and it doesnt have such issues

**Comment by sneakyevil** [comment]
Then use SilentPatch, nobody is forcing you to use GangstaPatch.
